# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/eduardo/29F419E21696543C/Projects/Pessoal/ParadiseEngine/pe

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/eduardo/29F419E21696543C/Projects/Pessoal/ParadiseEngine/pe

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/eduardo/29F419E21696543C/Projects/Pessoal/ParadiseEngine/pe/CMakeFiles /media/eduardo/29F419E21696543C/Projects/Pessoal/ParadiseEngine/pe/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/eduardo/29F419E21696543C/Projects/Pessoal/ParadiseEngine/pe/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SparseVoxelOctree

# Build rule for target.
SparseVoxelOctree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SparseVoxelOctree
.PHONY : SparseVoxelOctree

# fast build rule for target.
SparseVoxelOctree/fast:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/build
.PHONY : SparseVoxelOctree/fast

#=============================================================================
# Target rules for targets named dep

# Build rule for target.
dep: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dep
.PHONY : dep

# fast build rule for target.
dep/fast:
	$(MAKE) -f dep/CMakeFiles/dep.dir/build.make dep/CMakeFiles/dep.dir/build
.PHONY : dep/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f dep/glfw/src/CMakeFiles/glfw.dir/build.make dep/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) -f dep/spdlog/CMakeFiles/spdlog.dir/build.make dep/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named volk

# Build rule for target.
volk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 volk
.PHONY : volk

# fast build rule for target.
volk/fast:
	$(MAKE) -f dep/volk/CMakeFiles/volk.dir/build.make dep/volk/CMakeFiles/volk.dir/build
.PHONY : volk/fast

#=============================================================================
# Target rules for targets named shader_gen

# Build rule for target.
shader_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shader_gen
.PHONY : shader_gen

# fast build rule for target.
shader_gen/fast:
	$(MAKE) -f shader/CMakeFiles/shader_gen.dir/build.make shader/CMakeFiles/shader_gen.dir/build
.PHONY : shader_gen/fast

src/Application.o: src/Application.cpp.o

.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i

.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s

.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Counter.o: src/Counter.cpp.o

.PHONY : src/Counter.o

# target to build an object file
src/Counter.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Counter.cpp.o
.PHONY : src/Counter.cpp.o

src/Counter.i: src/Counter.cpp.i

.PHONY : src/Counter.i

# target to preprocess a source file
src/Counter.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Counter.cpp.i
.PHONY : src/Counter.cpp.i

src/Counter.s: src/Counter.cpp.s

.PHONY : src/Counter.s

# target to generate assembly for a file
src/Counter.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Counter.cpp.s
.PHONY : src/Counter.cpp.s

src/EnvironmentMap.o: src/EnvironmentMap.cpp.o

.PHONY : src/EnvironmentMap.o

# target to build an object file
src/EnvironmentMap.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/EnvironmentMap.cpp.o
.PHONY : src/EnvironmentMap.cpp.o

src/EnvironmentMap.i: src/EnvironmentMap.cpp.i

.PHONY : src/EnvironmentMap.i

# target to preprocess a source file
src/EnvironmentMap.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/EnvironmentMap.cpp.i
.PHONY : src/EnvironmentMap.cpp.i

src/EnvironmentMap.s: src/EnvironmentMap.cpp.s

.PHONY : src/EnvironmentMap.s

# target to generate assembly for a file
src/EnvironmentMap.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/EnvironmentMap.cpp.s
.PHONY : src/EnvironmentMap.cpp.s

src/ImGuiRenderer.o: src/ImGuiRenderer.cpp.o

.PHONY : src/ImGuiRenderer.o

# target to build an object file
src/ImGuiRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/ImGuiRenderer.cpp.o
.PHONY : src/ImGuiRenderer.cpp.o

src/ImGuiRenderer.i: src/ImGuiRenderer.cpp.i

.PHONY : src/ImGuiRenderer.i

# target to preprocess a source file
src/ImGuiRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/ImGuiRenderer.cpp.i
.PHONY : src/ImGuiRenderer.cpp.i

src/ImGuiRenderer.s: src/ImGuiRenderer.cpp.s

.PHONY : src/ImGuiRenderer.s

# target to generate assembly for a file
src/ImGuiRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/ImGuiRenderer.cpp.s
.PHONY : src/ImGuiRenderer.cpp.s

src/ImGuiUtil.o: src/ImGuiUtil.cpp.o

.PHONY : src/ImGuiUtil.o

# target to build an object file
src/ImGuiUtil.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/ImGuiUtil.cpp.o
.PHONY : src/ImGuiUtil.cpp.o

src/ImGuiUtil.i: src/ImGuiUtil.cpp.i

.PHONY : src/ImGuiUtil.i

# target to preprocess a source file
src/ImGuiUtil.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/ImGuiUtil.cpp.i
.PHONY : src/ImGuiUtil.cpp.i

src/ImGuiUtil.s: src/ImGuiUtil.cpp.s

.PHONY : src/ImGuiUtil.s

# target to generate assembly for a file
src/ImGuiUtil.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/ImGuiUtil.cpp.s
.PHONY : src/ImGuiUtil.cpp.s

src/Lighting.o: src/Lighting.cpp.o

.PHONY : src/Lighting.o

# target to build an object file
src/Lighting.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Lighting.cpp.o
.PHONY : src/Lighting.cpp.o

src/Lighting.i: src/Lighting.cpp.i

.PHONY : src/Lighting.i

# target to preprocess a source file
src/Lighting.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Lighting.cpp.i
.PHONY : src/Lighting.cpp.i

src/Lighting.s: src/Lighting.cpp.s

.PHONY : src/Lighting.s

# target to generate assembly for a file
src/Lighting.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Lighting.cpp.s
.PHONY : src/Lighting.cpp.s

src/LoaderThread.o: src/LoaderThread.cpp.o

.PHONY : src/LoaderThread.o

# target to build an object file
src/LoaderThread.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/LoaderThread.cpp.o
.PHONY : src/LoaderThread.cpp.o

src/LoaderThread.i: src/LoaderThread.cpp.i

.PHONY : src/LoaderThread.i

# target to preprocess a source file
src/LoaderThread.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/LoaderThread.cpp.i
.PHONY : src/LoaderThread.cpp.i

src/LoaderThread.s: src/LoaderThread.cpp.s

.PHONY : src/LoaderThread.s

# target to generate assembly for a file
src/LoaderThread.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/LoaderThread.cpp.s
.PHONY : src/LoaderThread.cpp.s

src/Octree.o: src/Octree.cpp.o

.PHONY : src/Octree.o

# target to build an object file
src/Octree.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Octree.cpp.o
.PHONY : src/Octree.cpp.o

src/Octree.i: src/Octree.cpp.i

.PHONY : src/Octree.i

# target to preprocess a source file
src/Octree.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Octree.cpp.i
.PHONY : src/Octree.cpp.i

src/Octree.s: src/Octree.cpp.s

.PHONY : src/Octree.s

# target to generate assembly for a file
src/Octree.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Octree.cpp.s
.PHONY : src/Octree.cpp.s

src/OctreeBuilder.o: src/OctreeBuilder.cpp.o

.PHONY : src/OctreeBuilder.o

# target to build an object file
src/OctreeBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/OctreeBuilder.cpp.o
.PHONY : src/OctreeBuilder.cpp.o

src/OctreeBuilder.i: src/OctreeBuilder.cpp.i

.PHONY : src/OctreeBuilder.i

# target to preprocess a source file
src/OctreeBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/OctreeBuilder.cpp.i
.PHONY : src/OctreeBuilder.cpp.i

src/OctreeBuilder.s: src/OctreeBuilder.cpp.s

.PHONY : src/OctreeBuilder.s

# target to generate assembly for a file
src/OctreeBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/OctreeBuilder.cpp.s
.PHONY : src/OctreeBuilder.cpp.s

src/OctreeTracer.o: src/OctreeTracer.cpp.o

.PHONY : src/OctreeTracer.o

# target to build an object file
src/OctreeTracer.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/OctreeTracer.cpp.o
.PHONY : src/OctreeTracer.cpp.o

src/OctreeTracer.i: src/OctreeTracer.cpp.i

.PHONY : src/OctreeTracer.i

# target to preprocess a source file
src/OctreeTracer.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/OctreeTracer.cpp.i
.PHONY : src/OctreeTracer.cpp.i

src/OctreeTracer.s: src/OctreeTracer.cpp.s

.PHONY : src/OctreeTracer.s

# target to generate assembly for a file
src/OctreeTracer.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/OctreeTracer.cpp.s
.PHONY : src/OctreeTracer.cpp.s

src/PathTracer.o: src/PathTracer.cpp.o

.PHONY : src/PathTracer.o

# target to build an object file
src/PathTracer.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracer.cpp.o
.PHONY : src/PathTracer.cpp.o

src/PathTracer.i: src/PathTracer.cpp.i

.PHONY : src/PathTracer.i

# target to preprocess a source file
src/PathTracer.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracer.cpp.i
.PHONY : src/PathTracer.cpp.i

src/PathTracer.s: src/PathTracer.cpp.s

.PHONY : src/PathTracer.s

# target to generate assembly for a file
src/PathTracer.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracer.cpp.s
.PHONY : src/PathTracer.cpp.s

src/PathTracerThread.o: src/PathTracerThread.cpp.o

.PHONY : src/PathTracerThread.o

# target to build an object file
src/PathTracerThread.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracerThread.cpp.o
.PHONY : src/PathTracerThread.cpp.o

src/PathTracerThread.i: src/PathTracerThread.cpp.i

.PHONY : src/PathTracerThread.i

# target to preprocess a source file
src/PathTracerThread.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracerThread.cpp.i
.PHONY : src/PathTracerThread.cpp.i

src/PathTracerThread.s: src/PathTracerThread.cpp.s

.PHONY : src/PathTracerThread.s

# target to generate assembly for a file
src/PathTracerThread.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracerThread.cpp.s
.PHONY : src/PathTracerThread.cpp.s

src/PathTracerViewer.o: src/PathTracerViewer.cpp.o

.PHONY : src/PathTracerViewer.o

# target to build an object file
src/PathTracerViewer.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracerViewer.cpp.o
.PHONY : src/PathTracerViewer.cpp.o

src/PathTracerViewer.i: src/PathTracerViewer.cpp.i

.PHONY : src/PathTracerViewer.i

# target to preprocess a source file
src/PathTracerViewer.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracerViewer.cpp.i
.PHONY : src/PathTracerViewer.cpp.i

src/PathTracerViewer.s: src/PathTracerViewer.cpp.s

.PHONY : src/PathTracerViewer.s

# target to generate assembly for a file
src/PathTracerViewer.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/PathTracerViewer.cpp.s
.PHONY : src/PathTracerViewer.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Sobol.o: src/Sobol.cpp.o

.PHONY : src/Sobol.o

# target to build an object file
src/Sobol.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Sobol.cpp.o
.PHONY : src/Sobol.cpp.o

src/Sobol.i: src/Sobol.cpp.i

.PHONY : src/Sobol.i

# target to preprocess a source file
src/Sobol.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Sobol.cpp.i
.PHONY : src/Sobol.cpp.i

src/Sobol.s: src/Sobol.cpp.s

.PHONY : src/Sobol.s

# target to generate assembly for a file
src/Sobol.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Sobol.cpp.s
.PHONY : src/Sobol.cpp.s

src/UICamera.o: src/UICamera.cpp.o

.PHONY : src/UICamera.o

# target to build an object file
src/UICamera.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UICamera.cpp.o
.PHONY : src/UICamera.cpp.o

src/UICamera.i: src/UICamera.cpp.i

.PHONY : src/UICamera.i

# target to preprocess a source file
src/UICamera.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UICamera.cpp.i
.PHONY : src/UICamera.cpp.i

src/UICamera.s: src/UICamera.cpp.s

.PHONY : src/UICamera.s

# target to generate assembly for a file
src/UICamera.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UICamera.cpp.s
.PHONY : src/UICamera.cpp.s

src/UILighting.o: src/UILighting.cpp.o

.PHONY : src/UILighting.o

# target to build an object file
src/UILighting.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILighting.cpp.o
.PHONY : src/UILighting.cpp.o

src/UILighting.i: src/UILighting.cpp.i

.PHONY : src/UILighting.i

# target to preprocess a source file
src/UILighting.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILighting.cpp.i
.PHONY : src/UILighting.cpp.i

src/UILighting.s: src/UILighting.cpp.s

.PHONY : src/UILighting.s

# target to generate assembly for a file
src/UILighting.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILighting.cpp.s
.PHONY : src/UILighting.cpp.s

src/UILoader.o: src/UILoader.cpp.o

.PHONY : src/UILoader.o

# target to build an object file
src/UILoader.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILoader.cpp.o
.PHONY : src/UILoader.cpp.o

src/UILoader.i: src/UILoader.cpp.i

.PHONY : src/UILoader.i

# target to preprocess a source file
src/UILoader.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILoader.cpp.i
.PHONY : src/UILoader.cpp.i

src/UILoader.s: src/UILoader.cpp.s

.PHONY : src/UILoader.s

# target to generate assembly for a file
src/UILoader.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILoader.cpp.s
.PHONY : src/UILoader.cpp.s

src/UILog.o: src/UILog.cpp.o

.PHONY : src/UILog.o

# target to build an object file
src/UILog.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILog.cpp.o
.PHONY : src/UILog.cpp.o

src/UILog.i: src/UILog.cpp.i

.PHONY : src/UILog.i

# target to preprocess a source file
src/UILog.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILog.cpp.i
.PHONY : src/UILog.cpp.i

src/UILog.s: src/UILog.cpp.s

.PHONY : src/UILog.s

# target to generate assembly for a file
src/UILog.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UILog.cpp.s
.PHONY : src/UILog.cpp.s

src/UIOctreeTracer.o: src/UIOctreeTracer.cpp.o

.PHONY : src/UIOctreeTracer.o

# target to build an object file
src/UIOctreeTracer.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UIOctreeTracer.cpp.o
.PHONY : src/UIOctreeTracer.cpp.o

src/UIOctreeTracer.i: src/UIOctreeTracer.cpp.i

.PHONY : src/UIOctreeTracer.i

# target to preprocess a source file
src/UIOctreeTracer.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UIOctreeTracer.cpp.i
.PHONY : src/UIOctreeTracer.cpp.i

src/UIOctreeTracer.s: src/UIOctreeTracer.cpp.s

.PHONY : src/UIOctreeTracer.s

# target to generate assembly for a file
src/UIOctreeTracer.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UIOctreeTracer.cpp.s
.PHONY : src/UIOctreeTracer.cpp.s

src/UIPathTracer.o: src/UIPathTracer.cpp.o

.PHONY : src/UIPathTracer.o

# target to build an object file
src/UIPathTracer.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UIPathTracer.cpp.o
.PHONY : src/UIPathTracer.cpp.o

src/UIPathTracer.i: src/UIPathTracer.cpp.i

.PHONY : src/UIPathTracer.i

# target to preprocess a source file
src/UIPathTracer.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UIPathTracer.cpp.i
.PHONY : src/UIPathTracer.cpp.i

src/UIPathTracer.s: src/UIPathTracer.cpp.s

.PHONY : src/UIPathTracer.s

# target to generate assembly for a file
src/UIPathTracer.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/UIPathTracer.cpp.s
.PHONY : src/UIPathTracer.cpp.s

src/Voxelizer.o: src/Voxelizer.cpp.o

.PHONY : src/Voxelizer.o

# target to build an object file
src/Voxelizer.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Voxelizer.cpp.o
.PHONY : src/Voxelizer.cpp.o

src/Voxelizer.i: src/Voxelizer.cpp.i

.PHONY : src/Voxelizer.i

# target to preprocess a source file
src/Voxelizer.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Voxelizer.cpp.i
.PHONY : src/Voxelizer.cpp.i

src/Voxelizer.s: src/Voxelizer.cpp.s

.PHONY : src/Voxelizer.s

# target to generate assembly for a file
src/Voxelizer.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/Voxelizer.cpp.s
.PHONY : src/Voxelizer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/SparseVoxelOctree.dir/build.make CMakeFiles/SparseVoxelOctree.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SparseVoxelOctree"
	@echo "... dep"
	@echo "... glfw"
	@echo "... spdlog"
	@echo "... volk"
	@echo "... shader_gen"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Counter.o"
	@echo "... src/Counter.i"
	@echo "... src/Counter.s"
	@echo "... src/EnvironmentMap.o"
	@echo "... src/EnvironmentMap.i"
	@echo "... src/EnvironmentMap.s"
	@echo "... src/ImGuiRenderer.o"
	@echo "... src/ImGuiRenderer.i"
	@echo "... src/ImGuiRenderer.s"
	@echo "... src/ImGuiUtil.o"
	@echo "... src/ImGuiUtil.i"
	@echo "... src/ImGuiUtil.s"
	@echo "... src/Lighting.o"
	@echo "... src/Lighting.i"
	@echo "... src/Lighting.s"
	@echo "... src/LoaderThread.o"
	@echo "... src/LoaderThread.i"
	@echo "... src/LoaderThread.s"
	@echo "... src/Octree.o"
	@echo "... src/Octree.i"
	@echo "... src/Octree.s"
	@echo "... src/OctreeBuilder.o"
	@echo "... src/OctreeBuilder.i"
	@echo "... src/OctreeBuilder.s"
	@echo "... src/OctreeTracer.o"
	@echo "... src/OctreeTracer.i"
	@echo "... src/OctreeTracer.s"
	@echo "... src/PathTracer.o"
	@echo "... src/PathTracer.i"
	@echo "... src/PathTracer.s"
	@echo "... src/PathTracerThread.o"
	@echo "... src/PathTracerThread.i"
	@echo "... src/PathTracerThread.s"
	@echo "... src/PathTracerViewer.o"
	@echo "... src/PathTracerViewer.i"
	@echo "... src/PathTracerViewer.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Sobol.o"
	@echo "... src/Sobol.i"
	@echo "... src/Sobol.s"
	@echo "... src/UICamera.o"
	@echo "... src/UICamera.i"
	@echo "... src/UICamera.s"
	@echo "... src/UILighting.o"
	@echo "... src/UILighting.i"
	@echo "... src/UILighting.s"
	@echo "... src/UILoader.o"
	@echo "... src/UILoader.i"
	@echo "... src/UILoader.s"
	@echo "... src/UILog.o"
	@echo "... src/UILog.i"
	@echo "... src/UILog.s"
	@echo "... src/UIOctreeTracer.o"
	@echo "... src/UIOctreeTracer.i"
	@echo "... src/UIOctreeTracer.s"
	@echo "... src/UIPathTracer.o"
	@echo "... src/UIPathTracer.i"
	@echo "... src/UIPathTracer.s"
	@echo "... src/Voxelizer.o"
	@echo "... src/Voxelizer.i"
	@echo "... src/Voxelizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

